<?php
declare(strict_types=1);

/**
 * Iyapayao Booster — Installer
 * Run this script once to create all database tables and the default admin account.
 * Delete or rename this file after installation for security.
 */

// Simple lock check
$lock_file = __DIR__ . '/.installed';
if (file_exists($lock_file)) {
    die('<p style="font-family:sans-serif;color:red;padding:20px">
        The panel is already installed. Please delete <code>install/.installed</code> to re-run the installer.
    </p>');
}

$step    = (int)($_GET['step'] ?? 1);
$errors  = [];
$success = false;

// ----------------------------------------------------------------
// Step 2 — process installation
// ----------------------------------------------------------------
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $db_host     = trim($_POST['db_host']     ?? 'localhost');
    $db_port     = trim($_POST['db_port']     ?? '3306');
    $db_name     = trim($_POST['db_name']     ?? '');
    $db_user     = trim($_POST['db_user']     ?? '');
    $db_pass     = $_POST['db_pass']          ?? '';
    $admin_user  = trim($_POST['admin_user']  ?? 'admin');
    $admin_email = trim($_POST['admin_email'] ?? '');
    $admin_pass  = $_POST['admin_pass']       ?? '';
    $site_name   = trim($_POST['site_name']   ?? 'Iyapayao Booster');

    if ($db_name === '' || $db_user === '') {
        $errors[] = 'Database name and user are required.';
    }
    if (!filter_var($admin_email, FILTER_VALIDATE_EMAIL)) {
        $errors[] = 'Please enter a valid admin email.';
    }
    if (strlen($admin_pass) < 8) {
        $errors[] = 'Admin password must be at least 8 characters.';
    }

    if (empty($errors)) {
        try {
            // Connect (create DB if not exists)
            $dsn = "mysql:host=$db_host;port=$db_port;charset=utf8mb4";
            $pdo = new PDO($dsn, $db_user, $db_pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `$db_name`");

            // Run schema
            $schema = file_get_contents(__DIR__ . '/../schema.sql');
            if ($schema === false) {
                throw new RuntimeException('Cannot read schema.sql');
            }

            // Execute each statement — strip SQL comments before checking emptiness
            foreach (explode(';', $schema) as $sql) {
                // Remove leading/trailing whitespace and single-line comment lines
                $sql = preg_replace('/^--[^\n]*$/m', '', $sql) ?? $sql;
                $sql = trim($sql);
                if ($sql === '') continue;
                $pdo->exec($sql);
            }

            // Add unique index for service_id if not present
            try {
                $pdo->exec('ALTER TABLE services ADD UNIQUE INDEX `service_id_unique` (`service_id`)');
            } catch (PDOException $e) {
                // Index may already exist — ignore
            }

            // Insert admin user
            $hashed  = password_hash($admin_pass, PASSWORD_BCRYPT);
            $api_key = bin2hex(random_bytes(32));
            $stmt    = $pdo->prepare(
                'INSERT INTO users (username, email, password, role, status, api_key, created_at, updated_at)
                 VALUES (?, ?, ?, \'admin\', \'active\', ?, NOW(), NOW())
                 ON DUPLICATE KEY UPDATE
                   email    = VALUES(email),
                   password = VALUES(password),
                   role     = \'admin\',
                   api_key  = VALUES(api_key),
                   updated_at = NOW()'
            );
            $stmt->execute([$admin_user, $admin_email, $hashed, $api_key]);

            // Upsert site name
            $pdo->prepare(
                'INSERT INTO settings (setting_key, setting_value) VALUES (\'site_name\', ?)
                 ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)'
            )->execute([$site_name]);

            // Write config file
            $config_content = <<<PHP
<?php
// Auto-generated by installer — do not edit manually
define('DB_HOST',    '$db_host');
define('DB_PORT',    '$db_port');
define('DB_NAME',    '$db_name');
define('DB_USER',    '$db_user');
define('DB_PASS',    '$db_pass');
define('DB_CHARSET', 'utf8mb4');

define('APP_ROOT', dirname(__DIR__));
define('APP_URL',  (isset(\$_SERVER['HTTPS']) && \$_SERVER['HTTPS'] === 'on' ? 'https' : 'http') .
                   '://' . (\$_SERVER['HTTP_HOST'] ?? 'localhost'));

function get_db(): PDO
{
    static \$pdo = null;
    if (\$pdo === null) {
        \$dsn = sprintf('mysql:host=%s;port=%s;dbname=%s;charset=%s', DB_HOST, DB_PORT, DB_NAME, DB_CHARSET);
        \$pdo = new PDO(\$dsn, DB_USER, DB_PASS, [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
        ]);
    }
    return \$pdo;
}
function get_setting(string \$key, string \$default = ''): string
{
    static \$cache = [];
    if (isset(\$cache[\$key])) return \$cache[\$key];
    try {
        \$stmt = get_db()->prepare('SELECT setting_value FROM settings WHERE setting_key = ? LIMIT 1');
        \$stmt->execute([\$key]);
        \$row  = \$stmt->fetch();
        \$cache[\$key] = \$row ? (string)\$row['setting_value'] : \$default;
    } catch (PDOException \$e) { \$cache[\$key] = \$default; }
    return \$cache[\$key];
}
function set_setting(string \$key, string \$value): void
{
    get_db()->prepare('INSERT INTO settings (setting_key, setting_value) VALUES (?, ?)
        ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)')->execute([\$key, \$value]);
}
PHP;

            file_put_contents(__DIR__ . '/../config/database.php', $config_content);

            // Create lock file
            file_put_contents($lock_file, date('Y-m-d H:i:s'));

            $success = true;
        } catch (PDOException $e) {
            $errors[] = 'Database error: ' . htmlspecialchars($e->getMessage(), ENT_QUOTES);
        } catch (RuntimeException $e) {
            $errors[] = $e->getMessage();
        }
    }
}

?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iyapayao Booster — Installer</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #f5f7fa;
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            padding: 24px;
        }
        .card {
            background: #fff;
            border-radius: 12px;
            box-shadow: 0 2px 20px rgba(0,0,0,.1);
            padding: 40px;
            width: 100%;
            max-width: 500px;
        }
        h1 { font-size: 1.5rem; color: #4361ee; margin-bottom: 6px; }
        p.subtitle { color: #6c757d; font-size: .9rem; margin-bottom: 28px; }
        .form-group { margin-bottom: 16px; }
        label { display: block; font-weight: 600; font-size: .85rem; margin-bottom: 5px; }
        input[type="text"],input[type="email"],input[type="password"],input[type="number"] {
            width: 100%;
            padding: 9px 12px;
            border: 1px solid #e9ecef;
            border-radius: 6px;
            font-size: .9rem;
        }
        input:focus { outline: none; border-color: #4361ee; box-shadow: 0 0 0 3px rgba(67,97,238,.15); }
        button {
            width: 100%;
            padding: 11px;
            background: #4361ee;
            color: #fff;
            border: none;
            border-radius: 6px;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            margin-top: 8px;
        }
        button:hover { background: #3a56d4; }
        .alert { padding: 12px 14px; border-radius: 6px; margin-bottom: 16px; font-size: .88rem; }
        .alert-danger  { background: #f8d7da; color: #721c24; border-left: 3px solid #dc3545; }
        .alert-success { background: #d4edda; color: #155724; border-left: 3px solid #28a745; }
        .sep { border-top: 1px solid #e9ecef; margin: 24px 0 20px; }
        h2 { font-size: 1rem; color: #6c757d; margin-bottom: 14px; font-weight: 600; }
        .form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
        a { color: #4361ee; }
        small { font-size: .78rem; color: #6c757d; }
    </style>
</head>
<body>
<div class="card">
    <h1>⚡ Iyapayao Booster</h1>
    <p class="subtitle">First-time installation wizard</p>

    <?php foreach ($errors as $err): ?>
        <div class="alert alert-danger"><?= htmlspecialchars($err, ENT_QUOTES) ?></div>
    <?php endforeach; ?>

    <?php if ($success): ?>
        <div class="alert alert-success">
            <strong>Installation successful!</strong><br>
            Your panel is ready. Please delete or rename the <code>install/</code> directory.
        </div>
        <p>
            <a href="../auth/login.php">→ Go to Login</a>
        </p>
    <?php else: ?>
    <form method="POST" action="?step=2">
        <h2>Database Configuration</h2>
        <div class="form-row">
            <div class="form-group">
                <label for="db_host">Host</label>
                <input type="text" id="db_host" name="db_host"
                       value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost', ENT_QUOTES) ?>" required>
            </div>
            <div class="form-group">
                <label for="db_port">Port</label>
                <input type="number" id="db_port" name="db_port"
                       value="<?= htmlspecialchars($_POST['db_port'] ?? '3306', ENT_QUOTES) ?>" required>
            </div>
        </div>
        <div class="form-group">
            <label for="db_name">Database Name</label>
            <input type="text" id="db_name" name="db_name"
                   value="<?= htmlspecialchars($_POST['db_name'] ?? 'iyapayao_booster', ENT_QUOTES) ?>" required>
            <small>The installer will create this database if it does not exist.</small>
        </div>
        <div class="form-row">
            <div class="form-group">
                <label for="db_user">DB Username</label>
                <input type="text" id="db_user" name="db_user"
                       value="<?= htmlspecialchars($_POST['db_user'] ?? 'root', ENT_QUOTES) ?>" required>
            </div>
            <div class="form-group">
                <label for="db_pass">DB Password</label>
                <input type="password" id="db_pass" name="db_pass" autocomplete="new-password">
            </div>
        </div>

        <div class="sep"></div>
        <h2>Admin Account</h2>

        <div class="form-group">
            <label for="site_name">Site Name</label>
            <input type="text" id="site_name" name="site_name"
                   value="<?= htmlspecialchars($_POST['site_name'] ?? 'Iyapayao Booster', ENT_QUOTES) ?>" required>
        </div>
        <div class="form-group">
            <label for="admin_user">Admin Username</label>
            <input type="text" id="admin_user" name="admin_user"
                   value="<?= htmlspecialchars($_POST['admin_user'] ?? 'admin', ENT_QUOTES) ?>" required>
        </div>
        <div class="form-group">
            <label for="admin_email">Admin Email</label>
            <input type="email" id="admin_email" name="admin_email"
                   value="<?= htmlspecialchars($_POST['admin_email'] ?? '', ENT_QUOTES) ?>" required>
        </div>
        <div class="form-group">
            <label for="admin_pass">Admin Password</label>
            <input type="password" id="admin_pass" name="admin_pass" required
                   minlength="8" autocomplete="new-password">
            <small>Minimum 8 characters.</small>
        </div>

        <button type="submit">Install Iyapayao Booster</button>
    </form>
    <?php endif; ?>
</div>
</body>
</html>
